<!--
 * Awesconcepts.
 *
 * NOTICE OF LICENSE
 *
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Awesconcepts does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Awesconcepts does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   Awesconcepts
 * @package    Awesconcepts_Awestep
 * @author     Awesconcepts Team
 * @copyright  Copyright (c) 2014-2017 Awesconcepts. ( http://awesconcepts.com )
-->
<div class="admin__page-section-item order-shipping-method">
	<strong>
		<?php echo __('Delivery Date') ?>
	</strong>
	<span class="price"><?php echo $block->getDeliveryDate() ?></span>
</div>
<div class="admin__page-section-item order-shipping-method">
	<strong>
		<?php echo __('Delivery Comment:') ?>
	</strong>
	<address><?php echo $block->getDeliveryComment() ?></address>
</div>
<div class="admin__page-section-item order-shipping-method">
	
</div>